Replacing use of WGSIRequest.REQUEST attribute
When navigating to Mouse admin while running server, get AttributeError
from advanced_filters' admin.py, under adv_filters_handle():

data = request.POST if request.REQUEST.get(
AttributeError: 'WGSIRequest' object has no attribute 'REQUEST'

request is WSGIRequest object, which inherits from the
django.http.HttpRequest class. This class used to have a REQUEST
attribute, but it has been deprecated in Django 1.9.

Replaced REQUEST with POST (as recommended by Django 1.9 documentation)